cnn_basic:
	../../src/table_extraction/table_extraction_cnn.py --pdf_dir ./test.pdf --work_dir ./ --first_table_page 2 --last_table_page 5
cnn_advanced:
	../../src/table_extraction/table_extraction.py --pdf_dir ./test.pdf --work_dir ./ --first_table_page 2 --last_table_page 5	
cnn_yolo:
	../../src/table_extraction/table_extraction.py --pdf_dir ./test.pdf --work_dir ./ --first_table_page 4 --last_table_page 4 --use_yolo True
clean:
	../../src/table_extraction/clean_table_extraction.py --work_dir ./