table:
	../../src/table_extraction/table_extraction.py --weight_dir ./Table_extract_robust --pdf_dir ./test.pdf --work_dir ./ --first_table_page 2 --last_table_page 4
clean:
	../../src/table_extraction/clean_table_extraction.py --work_dir ./